config/routes.rb
Rails.application.routes.draw do
  resources :vehicules
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicule.rb
class Vehicule < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/vehicules_controller.rb
class VehiculesController < InheritedResources::Base
  def index
    @vehicules = Vehicule.where(["owner_name LIKE ?", "%#{params[:search]}%"])
  end
  private

    def vehicule_params
      params.require(:vehicule).permit(:date, :owner_name, :N°cin, :vehicules_type, :mark, :color, :N°engine)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vehicules_helper.rb
module VehiculesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emat</title>

    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title  -->
    <title>Immatric - Site de recherche | FBI</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Favicon  -->
    <link rel="icon" href="img/core-img/favicon.ico">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="css/core-style.css">
    <link rel="stylesheet" href="style.css">

    <!-- Responsive CSS -->
    <link href="css/responsive.css" rel="stylesheet">
    <!-- font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  </head>

  <body>
    <div class="whole">
      <div class="lds-grid"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
    </div>
    <div class="logotext">
      <h1>IMMATRIC</h1>
    </div>
    <%= yield %>

    <!-- jQuery (Necessary for All JavaScript Plugins) -->
    <script src="js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Plugins js -->
    <script src="js/plugins.js"></script>
    <!-- Active js -->
    <script src="js/active.js"></script>
  </body>
</html>

app/views/vehicules/_form.html.erb
<%= form_with(model: vehicule, local: true) do |form| %>
  <% if vehicule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicule.errors.count, "error") %> prohibited this vehicule from being saved:</h2>

      <ul>
      <% vehicule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :owner_name %>
    <%= form.text_field :owner_name %>
  </div>

  <div class="field">
    <%= form.label :N°cin %>
    <%= form.number_field :N°cin %>
  </div>

  <div class="field">
    <%= form.label :vehicules_type %>
    <%= form.text_field :vehicules_type %>
  </div>

  <div class="field">
    <%= form.label :mark %>
    <%= form.text_field :mark %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :N°engine %>
    <%= form.text_field :N°engine %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicules/edit.html.erb
<h1>Editing Vehicule</h1>

<%= render 'form', vehicule: @vehicule %>

<%= link_to 'Show', @vehicule %> |
<%= link_to 'Back', vehicules_path %>

app/views/vehicules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicules</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Owner name</th>
      <th>N°cin</th>
      <th>Vehicules type</th>
      <th>Mark</th>
      <th>Color</th>
      <th>N°engine</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicules.each do |vehicule| %>
      <tr>
        <td><%= vehicule.date %></td>
        <td><%= vehicule.owner_name %></td>
        <td><%= vehicule.N°cin %></td>
        <td><%= vehicule.vehicules_type %></td>
        <td><%= vehicule.mark %></td>
        <td><%= vehicule.color %></td>
        <td><%= vehicule.N°engine %></td>
        <td><%= link_to 'Show', vehicule %></td>
        <td></td>
      </tr>
    <% end %>
  
  </tbody>
</table>

<br>

app/views/vehicules/new.html.erb
<h1>New Vehicule</h1>

<%= render 'form', vehicule: @vehicule %>

<%= link_to 'Back', vehicules_path %>

app/views/vehicules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @vehicule.date %>
</p>

<p>
  <strong>Owne name:</strong>
  <%= @vehicule.owner_name %>
</p>

<p>
  <strong>N°cin:</strong>
  <%= @vehicule.N°cin %>
</p>

<p>
  <strong>Vehicules type:</strong>
  <%= @vehicule.vehicules_type %>
</p>

<p>
  <strong>Mark:</strong>
  <%= @vehicule.mark %>
</p>

<p>
  <strong>Color:</strong>
  <%= @vehicule.color %>
</p>

<p>
  <strong>N°engine:</strong>
  <%= @vehicule.N°engine %>
</p>


<%= link_to 'Back', root_path %>